"""Pydantic models shared across BRIDGE services."""

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel


class RiskLevel(str, Enum):
    """Discrete risk strata for discharge outcomes."""

    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"


class SHARPContext(BaseModel):
    """Represents SHARP header values propagated from the EHR session."""

    patient_id: str
    fhir_base_url: str
    access_token: str
    encounter_id: Optional[str] = None
    practitioner_id: Optional[str] = None


class RiskDriver(BaseModel):
    """Scored criterion used to derive an overall risk classification."""

    criterion: str
    points: int
    fhir_evidence: List[str]


class RiskCard(BaseModel):
    """Aggregate risk summary with clinical and administrative flags."""

    patient_id: str
    lace_plus_score: int
    risk_level: RiskLevel
    primary_drivers: List[RiskDriver]
    medication_flags: List[str]
    sdoh_flags: List[str]
    pending_labs: List[str]
    missing_follow_ups: List[str]
    fhir_citations: List[str]

    model_config = {
        "json_schema_extra": {
            "example": {
                "patient_id": "bridge-demo-001",
                "lace_plus_score": 14,
                "risk_level": "HIGH",
                "primary_drivers": [
                    {
                        "criterion": "Length of stay 6 days",
                        "points": 3,
                        "fhir_evidence": ["Encounter/index-001"],
                    },
                    {
                        "criterion": "CHF exacerbation (acute admission)",
                        "points": 3,
                        "fhir_evidence": ["Condition/chf-001"],
                    },
                    {
                        "criterion": "Comorbidities: 3 active conditions",
                        "points": 3,
                        "fhir_evidence": [
                            "Condition/chf-001",
                            "Condition/dm-001",
                            "Condition/ckd-001",
                        ],
                    },
                    {
                        "criterion": "ED visits in last 6 months: 2",
                        "points": 2,
                        "fhir_evidence": ["Encounter/ed-1", "Encounter/ed-2"],
                    },
                ],
                "medication_flags": ["warfarin", "furosemide"],
                "sdoh_flags": [
                    "Z60.2: Living alone",
                    "Z59.0: Homelessness risk",
                ],
                "pending_labs": [
                    "Basic Metabolic Panel pending from 2026-04-30",
                ],
                "missing_follow_ups": [
                    "No follow-up appointments scheduled",
                ],
                "fhir_citations": [
                    "Encounter/index-001",
                    "MedicationRequest/warfarin-001",
                    "Observation/bmp-pending",
                ],
            }
        }
    }


class CarePlanAction(BaseModel):
    """Actionable care plan item derived from risk assessment."""

    action: str
    priority: str
    rationale: str
    risk_card_source: str


class CarePlanOutput(BaseModel):
    """Structured discharge care plan generated by BRIDGE."""

    patient_id: str
    actions: List[CarePlanAction]
    patient_instructions: str
    clinician_summary: str


class PCPHandoff(BaseModel):
    """Structured handoff package for primary care continuity."""

    patient_id: str
    hospitalization_reason: str
    medication_changes: List[str]
    pending_concerns: List[str]
    follow_up_priorities: List[str]
    handoff_letter: str


class GapAuditItem(BaseModel):
    """Single compliance check result for discharge documentation."""

    requirement: str
    status: str
    fhir_evidence: Optional[str] = None
    remediation: Optional[str] = None


class GapAuditOutput(BaseModel):
    """Summary of CMS documentation gap audit results."""

    patient_id: str
    overall_status: str
    items: List[GapAuditItem]
