"""Pydantic models shared across BRIDGE services."""

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Literal

from pydantic import BaseModel, field_validator

from common.validation import (
    validate_fhir_base_url,
    validate_optional_id,
    validate_patient_id,
)


class RiskLevel(str, Enum):
    """Discrete risk strata for discharge outcomes."""

    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"


class SHARPContext(BaseModel):
    """Represents SHARP header values propagated from the EHR session."""

    patient_id: str
    fhir_base_url: str
    access_token: str
    encounter_id: Optional[str] = None
    practitioner_id: Optional[str] = None

    @field_validator("patient_id")
    @classmethod
    def _validate_patient_id(cls, value: str) -> str:
        return validate_patient_id(value)

    @field_validator("fhir_base_url")
    @classmethod
    def _validate_fhir_base_url(cls, value: str) -> str:
        return validate_fhir_base_url(value)

    @field_validator("encounter_id")
    @classmethod
    def _validate_encounter_id(cls, value: Optional[str]) -> Optional[str]:
        return validate_optional_id(value, "encounter_id")

    @field_validator("practitioner_id")
    @classmethod
    def _validate_practitioner_id(cls, value: Optional[str]) -> Optional[str]:
        return validate_optional_id(value, "practitioner_id")


class RiskDriver(BaseModel):
    """Scored criterion used to derive an overall risk classification."""

    criterion: str
    points: int
    fhir_evidence: List[str]


class RiskCard(BaseModel):
    """Aggregate risk summary with clinical and administrative flags."""

    patient_id: str
    lace_plus_score: int
    risk_level: RiskLevel
    primary_drivers: List[RiskDriver]
    medication_flags: List[str]
    sdoh_flags: List[str]
    pending_labs: List[str]
    missing_follow_ups: List[str]
    fhir_citations: List[str]
    ai_risk_narrative: Optional[str] = None

    model_config = {
        "json_schema_extra": {
            "example": {
                "patient_id": "bridge-demo-001",
                "lace_plus_score": 14,
                "risk_level": "HIGH",
                "primary_drivers": [
                    {
                        "criterion": "Length of stay 6 days",
                        "points": 3,
                        "fhir_evidence": ["Encounter/index-001"],
                    },
                    {
                        "criterion": "CHF exacerbation (acute admission)",
                        "points": 3,
                        "fhir_evidence": ["Condition/chf-001"],
                    },
                    {
                        "criterion": "Comorbidities: 3 active conditions",
                        "points": 3,
                        "fhir_evidence": [
                            "Condition/chf-001",
                            "Condition/dm-001",
                            "Condition/ckd-001",
                        ],
                    },
                    {
                        "criterion": "ED visits in last 6 months: 2",
                        "points": 2,
                        "fhir_evidence": ["Encounter/ed-1", "Encounter/ed-2"],
                    },
                ],
                "medication_flags": ["warfarin", "furosemide"],
                "sdoh_flags": [
                    "Z60.2: Living alone",
                    "Z59.0: Homelessness risk",
                ],
                "pending_labs": [
                    "Basic Metabolic Panel pending from 2026-04-30",
                ],
                "missing_follow_ups": [
                    "No follow-up appointments scheduled",
                ],
                "fhir_citations": [
                    "Encounter/index-001",
                    "MedicationRequest/warfarin-001",
                    "Observation/bmp-pending",
                ],
            }
        }
    }


class CarePlanAction(BaseModel):
    """Actionable care plan item derived from risk assessment."""

    action: str
    priority: Literal["CRITICAL", "HIGH", "ROUTINE"]
    rationale: str
    risk_card_source: str


class CarePlanOutput(BaseModel):
    """Structured discharge care plan generated by BRIDGE."""

    patient_id: str
    actions: List[CarePlanAction]
    patient_instructions: str
    clinician_summary: str


class PCPHandoff(BaseModel):
    """Structured handoff package for primary care continuity."""

    patient_id: str
    hospitalization_reason: str
    medication_changes: List[str]
    pending_concerns: List[str]
    follow_up_priorities: List[str]
    handoff_letter: str


class GapAuditItem(BaseModel):
    """Single compliance check result for discharge documentation."""

    requirement: str
    status: Literal["PASS", "FAIL"]
    fhir_evidence: Optional[str] = None
    remediation: Optional[str] = None
    ai_severity: Optional[int] = None
    ai_clinical_context: Optional[str] = None
    ai_interdependencies: List[str] = []


class GapAuditOutput(BaseModel):
    """Summary of CMS documentation gap audit results."""

    patient_id: str
    overall_status: Literal["PASS", "ACTION_REQUIRED"]
    items: List[GapAuditItem]


# ── Debate Engine Models ──────────────────────────────────────────────────────

class AgentVote(BaseModel):
    """Vote cast by a specialist agent during clinical debate."""

    agent_name: str
    approval: bool
    confidence: float
    primary_concern: str
    detailed_reasoning: str
    suggested_actions: List[str]
    blocking_factors: List[str]
    fhir_evidence: List[str]


class ConsensusPlan(BaseModel):
    """Merged action plan synthesised from all agent votes."""

    mandatory_conditions: List[str]
    recommended_actions: List[str]
    monitoring_requirements: List[str]
    discharge_timeline: str


class DebateResult(BaseModel):
    """Full output of a multi-agent clinical debate."""

    patient_id: str
    consensus: Literal["APPROVE", "APPROVE_WITH_CONDITIONS", "OBJECT_WITH_CONCERNS", "BLOCK"]
    confidence: float
    vote_count: int
    approve_count: int
    block_count: int
    agent_votes: List[AgentVote]
    dissenting_votes: List[AgentVote]
    synthesis_plan: ConsensusPlan
    arbitration: str


# ── Explainability Models ─────────────────────────────────────────────────────

class ConfidenceFactor(BaseModel):
    """Single factor contributing to a confidence score."""

    factor: str
    weight: float
    certainty: Literal["Certain", "High", "Moderate", "Low"]


class ConfidenceExplanation(BaseModel):
    """Human-readable breakdown of a confidence score."""

    score: float
    level: Literal["VERY_HIGH", "HIGH", "MODERATE", "LOW"]
    key_factors: List[ConfidenceFactor]
    limitations: List[str]


class ReasonTrace(BaseModel):
    """Full decision chain for a single MCP tool call."""

    timestamp: str
    patient_id: str
    tool_called: str
    lace_plus_score: int
    risk_level: str
    reasoning_path: List[str]
    fallback_used: bool
    debate_result: Optional[DebateResult] = None
    confidence: Optional[ConfidenceExplanation] = None
